# Generated by Django 4.1.7 on 2023-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
